/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,jsx}', './src/**/*.{js,jsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        canvas: '#F8F9FB',
        surface: '#FFFFFF',
        ink: '#0A124B',
        charcoal: '#2A3038',
        graphite: '#4B5563',
        muted: '#68727E',
        silver: '#AEB5BD',
        line: '#E7EAEE',
        field: '#DDE5EC',
        accent: '#BFD1FF',
        action: '#B7CBFF',
        actionPressed: '#A9BEF8',
        homeBlue: '#0B5CD7',
        homeBlueSoft: '#BDD0FB',
        homeCard: '#FFFFFF',
        homeTint: '#E8F0FF',
        chip: '#DDE6ED',
        searchInput: '#FFFFFF',
        searchMuted: '#A5ADB6',
        chatInput: '#EEF3F8',
        unread: '#0B5CD7',
        contentCanvas: '#F8F9FA',
        contentLine: '#C1C6D7',
        contentCard: '#FFFFFF',
        contentSoft: '#F2F3F5',
        contentOrange: '#B95714',
        orgCanvas: '#F8F9FB',
        orgTeal: '#1EA597',
        orgPill: '#E8EDF2',
      },
      fontFamily: {
        display: ['System'],
        body: ['System'],
      },
      spacing: {
        screenX: '32px',
        cardX: '40px',
        section: '32px',
        inputH: '48px',
        buttonH: '48px',
      },
      borderRadius: {
        card: '10px',
        homeCard: '9px',
        homePanel: '14px',
        searchCard: '10px',
        bottomNav: '16px',
        input: '8px',
        button: '7px',
        brand: '10px',
      },
      fontSize: {
        hero: ['56px', { lineHeight: '62px', letterSpacing: '-2px' }],
        title: ['26px', { lineHeight: '32px', letterSpacing: '-0.6px' }],
        body: ['17px', { lineHeight: '27px' }],
        copy: ['15px', { lineHeight: '20px' }],
        label: ['10px', { lineHeight: '13px', letterSpacing: '0.7px' }],
        tiny: ['10px', { lineHeight: '12px', letterSpacing: '1.1px' }],
        nav: ['10px', { lineHeight: '12px', letterSpacing: '0.4px' }],
      },
      boxShadow: {
        soft: '0 18px 40px rgba(34, 44, 64, 0.10)',
        button: '0 10px 20px rgba(79, 111, 202, 0.24)',
        topBar: '0 -4px 20px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
};
